/**:
  ros__parameters:
    video_device: "/dev/elp_camera"
    framerate: 30.0
    image_width: 1280
    image_height: 720
    pixel_format: "mjpeg2rgb"
    camera_name: "elp_camera"
    camera_info_url: ""
    io_method: "mmap"
